
spring.application.name=fitflow

# Server
server.port=${SERVER_PORT}

# OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# JPA
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Multipart
app.upload.dir=${APP_UPLOAD_DIR}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# Rate limiting (requests per minute per IP)
# Login: max 5 intentos/min por IP
app.rate-limit.login.capacity=${RATE_LIMIT_LOGIN}

# Register / Onboarding: max 3 intentos/min por IP
app.rate-limit.register.capacity=${RATE_LIMIT_REGISTER}

# API general: max 200 req/min por IP
app.rate-limit.api.capacity=${RATE_LIMIT_API}

# Estas dos propiedades controlan qué información incluye Spring Boot en las respuestas de error,
# especialmente cuando ocurre una excepción y Spring devuelve un JSON de error
server.error.include-message=always
server.error.include-binding-errors=always

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
app.cors.allow-credentials=${CORS_ALLOW_CREDENTIALS}
