--
-- PostgreSQL database dump
--


-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

--
-- Name: access_devices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access_devices (
    access_device_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    device_type character varying(40) NOT NULL,
    location character varying(120),
    mac_address character varying(17),
    name character varying(100) NOT NULL,
    serial_number character varying(100),
    status boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    gym_id bigint NOT NULL
);


--
-- Name: access_devices_access_device_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.access_devices ALTER COLUMN access_device_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_devices_access_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    audit_log_id bigint NOT NULL,
    action character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    gym_id bigint,
    http_method character varying(10) NOT NULL,
    ip_address character varying(45),
    path character varying(300) NOT NULL,
    payload text,
    query_string character varying(500),
    status_code integer,
    user_agent character varying(300),
    user_gym_id bigint,
    user_id bigint,
    username character varying(80)
);


--
-- Name: audit_logs_audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN audit_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: benefits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.benefits (
    benefit_id bigint NOT NULL,
    description character varying(200) NOT NULL,
    gym_id bigint,
    name character varying(80) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: benefits_benefit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.benefits ALTER COLUMN benefit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.benefits_benefit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: countries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.countries (
    country_id bigint NOT NULL,
    code character varying(10),
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: countries_country_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.countries ALTER COLUMN country_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.currencies (
    currency_id bigint NOT NULL,
    code character varying(10) NOT NULL,
    name character varying(30) NOT NULL,
    status boolean
);


--
-- Name: currencies_currency_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.currencies ALTER COLUMN currency_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currencies_currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departaments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departaments (
    departament_id bigint NOT NULL,
    contry_id bigint NOT NULL,
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: departaments_departament_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departaments ALTER COLUMN departament_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departaments_departament_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_templates (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    html text NOT NULL,
    subject character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: email_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gym_payment_methods (
    gym_payment_method_id bigint NOT NULL,
    gym_id bigint NOT NULL,
    online boolean NOT NULL,
    payment_method_id bigint NOT NULL,
    status boolean NOT NULL
);


--
-- Name: gym_payment_methods_gym_payment_method_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gym_payment_methods ALTER COLUMN gym_payment_method_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_payment_methods_gym_payment_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_payment_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gym_payment_orders (
    gym_payment_order_id bigint NOT NULL,
    amount_in_cents bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(10) NOT NULL,
    customer_email character varying(150) NOT NULL,
    payment_gateway character varying(30) NOT NULL,
    payment_method_type character varying(20) NOT NULL,
    saas_plan_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    stripe_customer_id character varying(100),
    stripe_subscription_id character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    gym_id bigint NOT NULL
);


--
-- Name: gym_payment_orders_gym_payment_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gym_payment_orders ALTER COLUMN gym_payment_order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_payment_orders_gym_payment_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gym_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gym_subscriptions (
    gym_subscription_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_date date NOT NULL,
    notes character varying(255),
    saas_plan_id bigint,
    start_date date NOT NULL,
    status boolean NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    gym_id bigint NOT NULL
);


--
-- Name: gym_subscriptions_gym_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gym_subscriptions ALTER COLUMN gym_subscription_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gym_subscriptions_gym_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gyms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gyms (
    gym_id bigint NOT NULL,
    email character varying(100),
    gym_status character varying(20) NOT NULL,
    logo character varying(255) NOT NULL,
    municipalitie_id bigint NOT NULL,
    name character varying(60) NOT NULL,
    nit character varying(20) NOT NULL,
    phone character varying(13),
    status boolean NOT NULL,
    trial_expires_at timestamp(6) without time zone,
    parent_gym_id bigint,
    CONSTRAINT gyms_gym_status_check CHECK (((gym_status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('TRIAL'::character varying)::text, ('SUSPENDED'::character varying)::text])))
);


--
-- Name: gyms_gym_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gyms ALTER COLUMN gym_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gyms_gym_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventary_motion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventary_motion (
    inventary_motion_id bigint NOT NULL,
    amount integer NOT NULL,
    created_at date NOT NULL,
    motive character varying(20) NOT NULL,
    product_id bigint NOT NULL,
    type_motion_id bigint NOT NULL,
    updated_at date NOT NULL
);


--
-- Name: inventary_motion_inventary_motion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.inventary_motion ALTER COLUMN inventary_motion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventary_motion_inventary_motion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_benefits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_benefits (
    membership_benefit_id bigint NOT NULL,
    benefit_id bigint NOT NULL,
    membership_id bigint NOT NULL
);


--
-- Name: membership_benefits_membership_benefit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership_benefits ALTER COLUMN membership_benefit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_benefits_membership_benefit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_coachs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_coachs (
    membership_coach_id bigint NOT NULL,
    coach_id bigint NOT NULL,
    membership_id bigint NOT NULL,
    status boolean
);


--
-- Name: membership_coachs_membership_coach_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership_coachs ALTER COLUMN membership_coach_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_coachs_membership_coach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_prices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_prices (
    membership_price_id bigint NOT NULL,
    end_date date,
    membership_id bigint NOT NULL,
    price numeric(10,2) NOT NULL,
    start_date date NOT NULL
);


--
-- Name: membership_prices_membership_price_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership_prices ALTER COLUMN membership_price_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_prices_membership_price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_ratings (
    membership_rating_id bigint NOT NULL,
    coach_id bigint NOT NULL,
    date date NOT NULL,
    muscle_mass numeric(3,0) NOT NULL,
    observation character varying(200) NOT NULL,
    porcentage_fat numeric(3,0) NOT NULL,
    status boolean,
    user_gym_membership_id bigint NOT NULL,
    weight numeric(6,0) NOT NULL
);


--
-- Name: membership_ratings_membership_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership_ratings ALTER COLUMN membership_rating_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_ratings_membership_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: membership_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.membership_result (
    membership_result_id bigint NOT NULL,
    coach_id bigint NOT NULL,
    created_at date NOT NULL,
    end_fat numeric(3,0) NOT NULL,
    end_muscle_mass numeric(3,0) NOT NULL,
    end_weight numeric(6,0) NOT NULL,
    start_fat numeric(3,0) NOT NULL,
    start_muscle_mass numeric(3,0) NOT NULL,
    start_weight numeric(6,0) NOT NULL,
    status boolean,
    user_gym_membership_id bigint NOT NULL
);


--
-- Name: membership_result_membership_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.membership_result ALTER COLUMN membership_result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.membership_result_membership_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memberships (
    membership_id bigint NOT NULL,
    description character varying(200) NOT NULL,
    duration_day integer NOT NULL,
    gym_id bigint,
    name character varying(80) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: memberships_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memberships ALTER COLUMN membership_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipalities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.municipalities (
    municipalitie_id bigint NOT NULL,
    departament_id bigint NOT NULL,
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: municipalities_municipalitie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.municipalities ALTER COLUMN municipalitie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.municipalities_municipalitie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(36) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_gateways; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_gateways (
    payment_gateway_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: payment_gateways_payment_gateway_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_gateways ALTER COLUMN payment_gateway_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_gateways_payment_gateway_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_methods (
    payment_method_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: payment_methods_payment_method_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_methods ALTER COLUMN payment_method_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_methods_payment_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_statuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_statuses (
    payment_status_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: payment_statuses_payment_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_statuses ALTER COLUMN payment_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_statuses_payment_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    payment_id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method_id bigint NOT NULL,
    payment_reference character varying(30),
    payment_status_id bigint NOT NULL,
    status boolean NOT NULL,
    user_gym_id bigint NOT NULL
);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peoples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peoples (
    people_id bigint NOT NULL,
    email character varying(60),
    municipalitie_id bigint NOT NULL,
    names character varying(60) NOT NULL,
    num_document character varying(15) NOT NULL,
    phone character varying(30),
    photo character varying(254) NOT NULL,
    sexo_id bigint NOT NULL,
    status boolean NOT NULL,
    surnames character varying(60) NOT NULL,
    type_document_id bigint NOT NULL
);


--
-- Name: peoples_people_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.peoples ALTER COLUMN people_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peoples_people_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission_role (
    permission_role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: permission_role_permission_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permission_role ALTER COLUMN permission_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_role_permission_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    permission_id bigint NOT NULL,
    basic boolean NOT NULL,
    description character varying(200) NOT NULL,
    slug character varying(70) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: permissions_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permissions ALTER COLUMN permission_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    barcode character varying(100) NOT NULL,
    buy_praci numeric(10,0) NOT NULL,
    created_at date NOT NULL,
    currencie_id bigint NOT NULL,
    current_stock integer NOT NULL,
    description character varying(150) NOT NULL,
    gym_id bigint NOT NULL,
    min_stock integer NOT NULL,
    name character varying(60) NOT NULL,
    products_categirie_id bigint NOT NULL,
    sale_praci numeric(10,0) NOT NULL,
    status boolean,
    updated_at date NOT NULL
);


--
-- Name: products_categiries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products_categiries (
    products_categirie_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    status boolean
);


--
-- Name: products_categiries_products_categirie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products_categiries ALTER COLUMN products_categirie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_categiries_products_categirie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ratings (
    rating_id bigint NOT NULL,
    date date NOT NULL,
    muscle_mass numeric(3,0) NOT NULL,
    observation character varying(200) NOT NULL,
    porcentage_fat numeric(3,0) NOT NULL,
    status boolean,
    training_plan_id bigint NOT NULL,
    weight numeric(6,0) NOT NULL
);


--
-- Name: ratings_rating_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ratings ALTER COLUMN rating_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_rating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: result_plan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.result_plan (
    result_plan_id bigint NOT NULL,
    created_at date NOT NULL,
    end_fat numeric(3,0) NOT NULL,
    end_muscle_mass numeric(3,0) NOT NULL,
    end_weight numeric(6,0) NOT NULL,
    start_fat numeric(3,0) NOT NULL,
    start_muscle_mass numeric(3,0) NOT NULL,
    start_weight numeric(6,0) NOT NULL,
    status boolean,
    training_plan_id bigint NOT NULL
);


--
-- Name: result_plan_result_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.result_plan ALTER COLUMN result_plan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.result_plan_result_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    code character varying(60) NOT NULL,
    full_access boolean NOT NULL,
    gym_id bigint,
    is_staff boolean NOT NULL,
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rule_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rule_access (
    rule_access_id bigint NOT NULL,
    required_membership boolean NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: rule_access_rule_access_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rule_access ALTER COLUMN rule_access_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rule_access_rule_access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: runtine_coachs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runtine_coachs (
    runtine_coach_id bigint NOT NULL,
    coach_id bigint NOT NULL,
    runtine_id bigint NOT NULL,
    status boolean
);


--
-- Name: runtine_coachs_runtine_coach_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.runtine_coachs ALTER COLUMN runtine_coach_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.runtine_coachs_runtine_coach_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: runtines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runtines (
    runtine_id bigint NOT NULL,
    name character varying(50) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: runtines_runtine_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.runtines ALTER COLUMN runtine_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.runtines_runtine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saas_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saas_features (
    saas_feature_id bigint NOT NULL,
    code character varying(60) NOT NULL,
    description character varying(200),
    feature_type character varying(30) NOT NULL,
    name character varying(80) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: saas_features_saas_feature_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saas_features ALTER COLUMN saas_feature_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saas_features_saas_feature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saas_plan_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saas_plan_features (
    saas_plan_feature_id bigint NOT NULL,
    value_boolean boolean,
    value_number numeric(12,2),
    value_text character varying(100),
    saas_feature_id bigint NOT NULL,
    saas_plan_id bigint NOT NULL
);


--
-- Name: saas_plan_features_saas_plan_feature_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saas_plan_features ALTER COLUMN saas_plan_feature_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saas_plan_features_saas_plan_feature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saas_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saas_plans (
    saas_plan_id bigint NOT NULL,
    code character varying(40) NOT NULL,
    description character varying(200),
    name character varying(80) NOT NULL,
    num_days bigint NOT NULL,
    price numeric(12,2) NOT NULL,
    status boolean NOT NULL,
    stripe_price_id character varying(100),
    mp_preapproval_plan_id character varying(200),
    billing_cycle character varying(20)
);


--
-- Name: saas_plans_saas_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saas_plans ALTER COLUMN saas_plan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saas_plans_saas_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sale_details (
    sale_detail_id bigint NOT NULL,
    amount integer NOT NULL,
    product_id bigint NOT NULL,
    sale_id bigint NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL
);


--
-- Name: sale_details_sale_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sale_details ALTER COLUMN sale_detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_details_sale_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sales (
    sale_id bigint NOT NULL,
    change_amount numeric(12,2),
    gym_id bigint NOT NULL,
    notes character varying(200),
    paid_with numeric(12,2),
    payment_method character varying(50) NOT NULL,
    sale_date timestamp(6) without time zone NOT NULL,
    seller_id bigint,
    status boolean NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    total numeric(12,2) NOT NULL
);


--
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales ALTER COLUMN sale_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_logs (
    session_log_id bigint NOT NULL,
    end_date date,
    start_date date NOT NULL,
    user_gym_id bigint NOT NULL
);


--
-- Name: session_logs_session_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_logs ALTER COLUMN session_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_logs_session_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sexos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sexos (
    sexo_id bigint NOT NULL,
    code character varying(10),
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: sexos_sexo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sexos ALTER COLUMN sexo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sexos_sexo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_plans (
    training_plan_id bigint NOT NULL,
    end_date date NOT NULL,
    runtine_coach_id bigint NOT NULL,
    start_date date NOT NULL,
    status boolean,
    user_gym_id bigint NOT NULL
);


--
-- Name: training_plans_training_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_plans ALTER COLUMN training_plan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_plans_training_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.type_documents (
    type_document_id bigint NOT NULL,
    code character varying(10),
    name character varying(60) NOT NULL,
    status boolean NOT NULL
);


--
-- Name: type_documents_type_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.type_documents ALTER COLUMN type_document_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_documents_type_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: type_motions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.type_motions (
    type_motion_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    status boolean
);


--
-- Name: type_motions_type_motion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.type_motions ALTER COLUMN type_motion_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.type_motions_type_motion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_gym_membership; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_gym_membership (
    user_gym_membership_id bigint NOT NULL,
    end_date date NOT NULL,
    membership_id bigint NOT NULL,
    payment_preci numeric(10,2) NOT NULL,
    start_date date NOT NULL,
    status boolean NOT NULL,
    user_gym_id bigint NOT NULL
);


--
-- Name: user_gym_membership_user_gym_membership_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_gym_membership ALTER COLUMN user_gym_membership_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_gym_membership_user_gym_membership_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_payment_methods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_payment_methods (
    user_payment_method_id bigint NOT NULL,
    created_at date NOT NULL,
    expired_date character varying(6) NOT NULL,
    masked_pan character varying(4) NOT NULL,
    payment_gateway_id bigint NOT NULL,
    status boolean,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_payment_methods_user_payment_method_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_payment_methods ALTER COLUMN user_payment_method_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_payment_methods_user_payment_method_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    password character varying(100),
    people_id bigint NOT NULL
);


--
-- Name: users_gym_role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_gym_role (
    user_gym_role_id bigint NOT NULL,
    role_id bigint NOT NULL,
    user_gym_id bigint NOT NULL
);


--
-- Name: users_gym_role_user_gym_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_gym_role ALTER COLUMN user_gym_role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_gym_role_user_gym_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_gyms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_gyms (
    user_gym_id bigint NOT NULL,
    fingerprint bytea,
    gym_id bigint NOT NULL,
    status boolean NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: users_gyms_user_gym_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_gyms ALTER COLUMN user_gym_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_gyms_user_gym_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: access_devices access_devices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_devices
    ADD CONSTRAINT access_devices_pkey PRIMARY KEY (access_device_id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_log_id);


--
-- Name: benefits benefits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.benefits
    ADD CONSTRAINT benefits_pkey PRIMARY KEY (benefit_id);


--
-- Name: countries countries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (country_id);


--
-- Name: currencies currencies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.currencies
    ADD CONSTRAINT currencies_pkey PRIMARY KEY (currency_id);


--
-- Name: departaments departaments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departaments
    ADD CONSTRAINT departaments_pkey PRIMARY KEY (departament_id);


--
-- Name: email_templates email_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);


--
-- Name: gym_payment_methods gym_payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gym_payment_methods
    ADD CONSTRAINT gym_payment_methods_pkey PRIMARY KEY (gym_payment_method_id);


--
-- Name: gym_payment_orders gym_payment_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gym_payment_orders
    ADD CONSTRAINT gym_payment_orders_pkey PRIMARY KEY (gym_payment_order_id);


--
-- Name: gym_subscriptions gym_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gym_subscriptions
    ADD CONSTRAINT gym_subscriptions_pkey PRIMARY KEY (gym_subscription_id);


--
-- Name: gyms gyms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gyms
    ADD CONSTRAINT gyms_pkey PRIMARY KEY (gym_id);


--
-- Name: inventary_motion inventary_motion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventary_motion
    ADD CONSTRAINT inventary_motion_pkey PRIMARY KEY (inventary_motion_id);


--
-- Name: membership_benefits membership_benefits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_benefits
    ADD CONSTRAINT membership_benefits_pkey PRIMARY KEY (membership_benefit_id);


--
-- Name: membership_coachs membership_coachs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_coachs
    ADD CONSTRAINT membership_coachs_pkey PRIMARY KEY (membership_coach_id);


--
-- Name: membership_prices membership_prices_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_prices
    ADD CONSTRAINT membership_prices_pkey PRIMARY KEY (membership_price_id);


--
-- Name: membership_ratings membership_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_ratings
    ADD CONSTRAINT membership_ratings_pkey PRIMARY KEY (membership_rating_id);


--
-- Name: membership_result membership_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.membership_result
    ADD CONSTRAINT membership_result_pkey PRIMARY KEY (membership_result_id);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (membership_id);


--
-- Name: municipalities municipalities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipalities
    ADD CONSTRAINT municipalities_pkey PRIMARY KEY (municipalitie_id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: payment_gateways payment_gateways_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_gateways
    ADD CONSTRAINT payment_gateways_pkey PRIMARY KEY (payment_gateway_id);


--
-- Name: payment_methods payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_methods
    ADD CONSTRAINT payment_methods_pkey PRIMARY KEY (payment_method_id);


--
-- Name: payment_statuses payment_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_statuses
    ADD CONSTRAINT payment_statuses_pkey PRIMARY KEY (payment_status_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- Name: peoples peoples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peoples
    ADD CONSTRAINT peoples_pkey PRIMARY KEY (people_id);


--
-- Name: permission_role permission_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission_role
    ADD CONSTRAINT permission_role_pkey PRIMARY KEY (permission_role_id);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (permission_id);


--
-- Name: products_categiries products_categiries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products_categiries
    ADD CONSTRAINT products_categiries_pkey PRIMARY KEY (products_categirie_id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: ratings ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT ratings_pkey PRIMARY KEY (rating_id);


--
-- Name: result_plan result_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.result_plan
    ADD CONSTRAINT result_plan_pkey PRIMARY KEY (result_plan_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: rule_access rule_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rule_access
    ADD CONSTRAINT rule_access_pkey PRIMARY KEY (rule_access_id);


--
-- Name: runtine_coachs runtine_coachs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runtine_coachs
    ADD CONSTRAINT runtine_coachs_pkey PRIMARY KEY (runtine_coach_id);


--
-- Name: runtines runtines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runtines
    ADD CONSTRAINT runtines_pkey PRIMARY KEY (runtine_id);


--
-- Name: saas_features saas_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_features
    ADD CONSTRAINT saas_features_pkey PRIMARY KEY (saas_feature_id);


--
-- Name: saas_plan_features saas_plan_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_plan_features
    ADD CONSTRAINT saas_plan_features_pkey PRIMARY KEY (saas_plan_feature_id);


--
-- Name: saas_plans saas_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_plans
    ADD CONSTRAINT saas_plans_pkey PRIMARY KEY (saas_plan_id);


--
-- Name: sale_details sale_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sale_details
    ADD CONSTRAINT sale_details_pkey PRIMARY KEY (sale_detail_id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (sale_id);


--
-- Name: session_logs session_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_logs
    ADD CONSTRAINT session_logs_pkey PRIMARY KEY (session_log_id);


--
-- Name: sexos sexos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sexos
    ADD CONSTRAINT sexos_pkey PRIMARY KEY (sexo_id);


--
-- Name: training_plans training_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plans
    ADD CONSTRAINT training_plans_pkey PRIMARY KEY (training_plan_id);


--
-- Name: type_documents type_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type_documents
    ADD CONSTRAINT type_documents_pkey PRIMARY KEY (type_document_id);


--
-- Name: type_motions type_motions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.type_motions
    ADD CONSTRAINT type_motions_pkey PRIMARY KEY (type_motion_id);


--
-- Name: email_templates uk2k3pby9yobu7aa6kyfxijxxeb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT uk2k3pby9yobu7aa6kyfxijxxeb UNIQUE (code);


--
-- Name: users uk4gt2mblbi9mgocjptplntyefb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk4gt2mblbi9mgocjptplntyefb UNIQUE (people_id);


--
-- Name: saas_features uk61xsa1coiw42qe8yngyvt0hdu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_features
    ADD CONSTRAINT uk61xsa1coiw42qe8yngyvt0hdu UNIQUE (code);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: permissions ukdv6mwikptsu70hcrjq07sqsfy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT ukdv6mwikptsu70hcrjq07sqsfy UNIQUE (slug);


--
-- Name: saas_plans ukedwfkaaqoild5aeixiahgtsoc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_plans
    ADD CONSTRAINT ukedwfkaaqoild5aeixiahgtsoc UNIQUE (code);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: user_gym_membership user_gym_membership_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_gym_membership
    ADD CONSTRAINT user_gym_membership_pkey PRIMARY KEY (user_gym_membership_id);


--
-- Name: user_payment_methods user_payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_payment_methods
    ADD CONSTRAINT user_payment_methods_pkey PRIMARY KEY (user_payment_method_id);


--
-- Name: users_gym_role users_gym_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gym_role
    ADD CONSTRAINT users_gym_role_pkey PRIMARY KEY (user_gym_role_id);


--
-- Name: users_gyms users_gyms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_gyms
    ADD CONSTRAINT users_gyms_pkey PRIMARY KEY (user_gym_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_benefits_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_benefits_gym_id ON public.benefits USING btree (gym_id);


--
-- Name: idx_gym_payment_methods_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gym_payment_methods_gym_id ON public.gym_payment_methods USING btree (gym_id);


--
-- Name: idx_gym_payment_orders_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gym_payment_orders_gym_id ON public.gym_payment_orders USING btree (gym_id);


--
-- Name: idx_gym_payment_orders_stripe_customer_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gym_payment_orders_stripe_customer_id ON public.gym_payment_orders USING btree (stripe_customer_id);


--
-- Name: idx_gym_payment_orders_stripe_subscription_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_gym_payment_orders_stripe_subscription_id ON public.gym_payment_orders USING btree (stripe_subscription_id);


--
-- Name: idx_inventary_motion_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_inventary_motion_product_id ON public.inventary_motion USING btree (product_id);


--
-- Name: idx_membership_benefits_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_benefits_membership_id ON public.membership_benefits USING btree (membership_id);


--
-- Name: idx_membership_coachs_coach_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_coachs_coach_id ON public.membership_coachs USING btree (coach_id);


--
-- Name: idx_membership_coachs_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_coachs_membership_id ON public.membership_coachs USING btree (membership_id);


--
-- Name: idx_membership_prices_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_prices_membership_id ON public.membership_prices USING btree (membership_id);


--
-- Name: idx_membership_ratings_coach_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_ratings_coach_id ON public.membership_ratings USING btree (coach_id);


--
-- Name: idx_membership_ratings_user_gym_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_ratings_user_gym_membership_id ON public.membership_ratings USING btree (user_gym_membership_id);


--
-- Name: idx_membership_result_user_gym_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_membership_result_user_gym_membership_id ON public.membership_result USING btree (user_gym_membership_id);


--
-- Name: idx_memberships_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_memberships_gym_id ON public.memberships USING btree (gym_id);


--
-- Name: idx_payments_payment_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_payment_date ON public.payments USING btree (payment_date);


--
-- Name: idx_payments_payment_status_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_payment_status_id ON public.payments USING btree (payment_status_id);


--
-- Name: idx_payments_user_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payments_user_gym_id ON public.payments USING btree (user_gym_id);


--
-- Name: idx_peoples_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_peoples_email ON public.peoples USING btree (email);


--
-- Name: idx_peoples_num_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_peoples_num_document ON public.peoples USING btree (num_document);


--
-- Name: idx_permission_role_permission_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permission_role_permission_id ON public.permission_role USING btree (permission_id);


--
-- Name: idx_permission_role_role_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_permission_role_role_id ON public.permission_role USING btree (role_id);


--
-- Name: idx_products_barcode; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_barcode ON public.products USING btree (barcode);


--
-- Name: idx_products_current_stock; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_current_stock ON public.products USING btree (current_stock);


--
-- Name: idx_products_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_products_gym_id ON public.products USING btree (gym_id);


--
-- Name: idx_roles_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_roles_gym_id ON public.roles USING btree (gym_id);


--
-- Name: idx_saas_plan_features_plan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_saas_plan_features_plan_id ON public.saas_plan_features USING btree (saas_plan_id);


--
-- Name: idx_sale_details_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sale_details_product_id ON public.sale_details USING btree (product_id);


--
-- Name: idx_sale_details_sale_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sale_details_sale_id ON public.sale_details USING btree (sale_id);


--
-- Name: idx_sales_gym_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_gym_date ON public.sales USING btree (gym_id, sale_date);


--
-- Name: idx_sales_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_gym_id ON public.sales USING btree (gym_id);


--
-- Name: idx_sales_sale_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_sale_date ON public.sales USING btree (sale_date);


--
-- Name: idx_sales_seller_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sales_seller_id ON public.sales USING btree (seller_id);


--
-- Name: idx_session_logs_start_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_logs_start_date ON public.session_logs USING btree (start_date);


--
-- Name: idx_session_logs_user_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_logs_user_gym_id ON public.session_logs USING btree (user_gym_id);


--
-- Name: idx_session_logs_user_gym_start; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_session_logs_user_gym_start ON public.session_logs USING btree (user_gym_id, start_date);


--
-- Name: idx_user_gym_membership_end_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_gym_membership_end_date ON public.user_gym_membership USING btree (end_date);


--
-- Name: idx_user_gym_membership_membership_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_gym_membership_membership_id ON public.user_gym_membership USING btree (membership_id);


--
-- Name: idx_user_gym_membership_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_gym_membership_status ON public.user_gym_membership USING btree (status);


--
-- Name: idx_user_gym_membership_user_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_gym_membership_user_gym_id ON public.user_gym_membership USING btree (user_gym_id);


--
-- Name: idx_user_gym_membership_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_gym_membership_user_status ON public.user_gym_membership USING btree (user_gym_id, status);


--
-- Name: idx_user_payment_methods_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_payment_methods_user_id ON public.user_payment_methods USING btree (user_id);


--
-- Name: idx_users_gym_role_role_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_gym_role_role_id ON public.users_gym_role USING btree (role_id);


--
-- Name: idx_users_gym_role_user_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_gym_role_user_gym_id ON public.users_gym_role USING btree (user_gym_id);


--
-- Name: idx_users_gyms_gym_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_gyms_gym_id ON public.users_gyms USING btree (gym_id);


--
-- Name: idx_users_gyms_user_gym_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_gyms_user_gym_unique ON public.users_gyms USING btree (user_id, gym_id);


--
-- Name: idx_users_gyms_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_gyms_user_id ON public.users_gyms USING btree (user_id);


--
-- Name: gym_payment_orders fk373ac0nt8was7db5fx9n7ujgl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gym_payment_orders
    ADD CONSTRAINT fk373ac0nt8was7db5fx9n7ujgl FOREIGN KEY (gym_id) REFERENCES public.gyms(gym_id);


--
-- Name: permission_role fk3vhflqw0lwbwn49xqoivrtugt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission_role
    ADD CONSTRAINT fk3vhflqw0lwbwn49xqoivrtugt FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: permission_role fk6mg4g9rc8u87l0yavf8kjut05; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission_role
    ADD CONSTRAINT fk6mg4g9rc8u87l0yavf8kjut05 FOREIGN KEY (permission_id) REFERENCES public.permissions(permission_id);


--
-- Name: gyms fk8w4190wvw9sp9i96gf85pugne; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gyms
    ADD CONSTRAINT fk8w4190wvw9sp9i96gf85pugne FOREIGN KEY (parent_gym_id) REFERENCES public.gyms(gym_id);


--
-- Name: saas_plan_features fkaa454t9cw205qqkb6eqpp5uj2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_plan_features
    ADD CONSTRAINT fkaa454t9cw205qqkb6eqpp5uj2 FOREIGN KEY (saas_plan_id) REFERENCES public.saas_plans(saas_plan_id);


--
-- Name: gym_subscriptions fkfg0uejusyrc90yspnfkfcqr4d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gym_subscriptions
    ADD CONSTRAINT fkfg0uejusyrc90yspnfkfcqr4d FOREIGN KEY (gym_id) REFERENCES public.gyms(gym_id);


--
-- Name: access_devices fkhl6ah5l0ohfpusv9xioypqskf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access_devices
    ADD CONSTRAINT fkhl6ah5l0ohfpusv9xioypqskf FOREIGN KEY (gym_id) REFERENCES public.gyms(gym_id);


--
-- Name: users fkn1lj54bahv6ahvi76lrlcfndb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkn1lj54bahv6ahvi76lrlcfndb FOREIGN KEY (people_id) REFERENCES public.peoples(people_id);


--
-- Name: saas_plan_features fkpy4361ynsue68yfcjmeq4w776; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saas_plan_features
    ADD CONSTRAINT fkpy4361ynsue68yfcjmeq4w776 FOREIGN KEY (saas_feature_id) REFERENCES public.saas_features(saas_feature_id);


--
-- PostgreSQL database dump complete
--


